### ISSUE TITLE
Support Java11

### ISSUE THREAD

**Issue by Eyal-Shalev** [clj-commons/ring-buffer#10]
As described in [Clojure master fails on JDK 11 EA builds due to overloaded toArray in gvec.clj](https://dev.clojure.org/jira/browse/CLJ-2374), JDK 11 adds a new method with default impl `default <T> T[] toArray​(IntFunction<T[]> generator)` that the `ring-buffer` code does not support.

Suggestion: Use the patches described in the above link to support Java11

**Comment by BrunoBonacci** [comment]
this fix was released in `[amalloy/ring-buffer "1.2.2"]`
