### ISSUE TITLE
ClojureScript should be a provided dep

### ISSUE THREAD

**Issue by metametadata** [clj-commons/ring-buffer#14]
`org.clojure/clojurescript` should be  a `"provided"` dep. Otherwise, it is needlessly included in Clojure-only projects.

**Comment by BrunoBonacci** [comment]
Hi,
That's interesting...
It makes sense to me. However, I don't do much work on ClojureScript myself and I don't know what it is the common way to handle the ClojureScript dependency in the community.

Looking at clojurescript.org, both dependencies are added.
https://clojurescript.org/reference/dependencies#using-leiningen

And looking at other libraries in the Clojure ecosystem which are available on both: Clojure, and ClojureScript, they all seem to add both dependencies:

- [instaparse](https://github.com/Engelberg/instaparse/blob/master/project.clj)
- [Timbre](https://github.com/ptaoussanis/timbre/blob/master/project.clj)
- [Specter](https://github.com/redplanetlabs/specter/blob/master/project.clj)

However, looking at *core.async*, it does as you suggest.
- [core.async](https://github.com/clojure/core.async/blob/master/project.clj)

I don't have enough experience with ClojureScript to understand which one is better.
It was strange for myself too finding the dependency and having to add the exclusions in my projects. @danielcompton do you have any opinion on the matter?

**Comment by metametadata** [comment]
> they all seem to add both dependencies

Only in `:dev` profile which is not applied when library is published. `Specter` does not even require Clojure (e.g. see final `Dependencies` at https://clojars.org/com.rpl/specter).

> Looking at clojurescript.org, both dependencies are added.

It is because the example is a CLJS-only project. If a library is only for ClojureScript then it can specify the dep as required. (But maybe even that is not needed much as any consuming project will specify the "language" dep explicitly.)

I am personally used to always marking Clojure and/or CLJS deps as "provided" in my libs, e.g. see https://github.com/metametadata/clj-fakes/blob/master/project.clj.

**Comment by BrunoBonacci** [comment]
Hi,
I've set both dependencies as provided as you suggested.

Please have a look at https://github.com/clj-commons/ring-buffer/commit/722a6a220fe770145372f344df45e30d5ecb1b72 and let me know if that looks ok to you.

If it is ok, I'll tag and release.

**Comment by danielcompton** [comment]
Sorry for the delay, this change looks good to me. If it’s a ClojureScript only dependency then it doesn’t make a big difference whether the ClojureScript dependency is required or not, as the consumer will be picking their own version anyway. If it’s for Clojure and ClojureScript then making the dependencies provided is good as it means a Clojure project doesn’t need to include it.

**Comment by metametadata** [comment]
Looks good to me, thanks.

**Comment by BrunoBonacci** [comment]
Hi,
since there are no more changes, i've cut a new release for ring-buffer `1.3.1` with this change.

@danielcompton I still don't have the rights to push a new release to clojars, is this something you can grant me?

**Comment by danielcompton** [comment]
Sorry for the delay @BrunoBonacci, I've given you rights for this.

**Comment by BrunoBonacci** [comment]
released: https://clojars.org/amalloy/ring-buffer/versions/1.3.1

**Comment by metametadata** [comment]
Thank you.
