### ISSUE TITLE
Closing old buffer on empty

### ISSUE THREAD

**Issue by sirmspencer** [clj-commons/ring-buffer#15]
We are seeing really high memory when using this ring buffer.  I'm not an expert in the class you are using so I have a question for you.  It looks like empty creates a new ring buffer that is empty. How is empty disposing of the old buffer?  This looks like its not.

```
  (empty [this]
    (RingBuffer. 0 0 (vec (repeat (count buf) nil)) meta))
```

**Comment by BrunoBonacci** [comment]
The `ring-buffer` is an immutable persistent data structure based on the Clojure vectors, so once created cannot be changed. The ring-buffer creates an empty new buffer and if you don't have anything holding a reference to the previous buffer, then the Garbage Collector will release the memory.

So look back at the code where you use the buffer and make sure you are not keeping a reference anywhere

**Comment by sirmspencer** [comment]
Thanks for the explination!
